### ISSUE TITLE
哈喽，想问一下cgi文件是用什么工具反编译的呢？

### ISSUE THREAD

**Issue by shepherd168** [doudoudedi/ToTolink_EX200_Cmmand_Execute#1]
哈喽，想问一下cgi文件是用什么工具反编译的呢？

**Comment by doudoudedi** [comment]
我当时是使用的ghidra，其他工具应该可以的


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; good luck
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doudoudedi/ToTolink_EX200_Cmmand_Execute"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月4日(星期四) 下午5:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[doudoudedi/ToTolink_EX200_Cmmand_Execute] 哈喽，想问一下cgi文件是用什么工具反编译的呢？ (Issue #1)





 
哈喽，想问一下cgi文件是用什么工具反编译的呢？

**Comment by shepherd168** [comment]
谢谢解答，我试试ghidra
